name : Deploy To EC2 

on :
  push : 
    branches :
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: save private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH key to agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      # 1. 원격 EC2 서버에 접속하여 배포 작업
      - name : SSH(원격접속)로 EC2에 접속하기
        uses : appleboy/ssh-action@master
        env :           												
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
          DB_HOST: ${{ secrets.AWS_DB_ADDRESS }} 
          DB_USER: ${{ secrets.DB_USERNAME }}    
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SERVICE_NAME: ${{ secrets.DB_SERVICE_NAME }}
        with :
          host : ${{ secrets.AWS_WEB_ADDRESS }}
          username : ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script_stop : true
          script : |
            # 2. Git 레포지토리에서 최신 버전 Pull
            cd /home/ec2-user/Hairyz
            rm -rf src/main/resources/application.yml 				 
            git pull origin main

            # 3. 환경 변수 설정
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml

            # 4. Gradle 빌드 수행
            ./gradlew clean build

            # 5. 파일 이름 변경
            mv build/libs/*SNAPSHOT.war build/libs/project.war

            # 6. war 파일 이동 
            mv /home/ec2-user/Hairyz/build/libs/project.war /home/ec2-user/apache-tomcat-10.1.31/webapps/

            # 7. DB 연결 테스트 (오라클)
            echo "Testing Oracle DB connection"
            echo "SELECT * FROM member;" | sqlplus -S $DB_USER/$DB_PASSWORD@$DB_HOST:1521/$DB_SERVICE_NAME

            # 8. 톰캣 재시작
            sudo /home/ec2-user/apache-tomcat-10.1.31/bin/shutdown.sh
            sudo /home/ec2-user/apache-tomcat-10.1.31/bin/startup.sh