name: Deploy

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거됨

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and run tests
        env:
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          ./gradlew build
