name : Deploy To EC2 

on :
  push : 
    branches :
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 원격 EC2 서버에 접속하여 배포 작업
      - name : SSH(원격접속)로 EC2에 접속하기
        uses : appleboy/ssh-action@v1.1.0
        env :           												
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }} 
        with :
          host : ${{ secrets.AWS_WEB_ADDRESS }}
          username : ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script_stop : true
          script : |
            # 2. Git 레포지토리에서 최신 버전 Pull
            cd /home/ec2-user/Hairyz
            rm -rf src/main/resources/application.yml      				 
            git pull origin main

            # 3. 환경 변수 설정
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            
            # 4. Gradle 빌드 수행
            ./gradlew clean build

            # 5. Tomcat 포트 8081에서 이전 프로세스 종료
            sudo fuser -k -n tcp 8081 || true

            # 톰캣 재시작
            sudo /home/${{ secrets.AWS_USER }}/apache-tomcat-10.1.31/bin/shutdown.sh
            sudo /home/${{ secrets.AWS_USER }}/apache-tomcat-10.1.31/bin/startup.sh