name : Deploy To EC2 

on :
  push : 
    branches :
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: save private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH key to agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      # 1. 원격 EC2 서버에 접속하여 배포 작업
      - name : SSH 접속 (EC2)
        uses : appleboy/ssh-action@master
        env : 
          DB_HOST: ${{ secrets.AWS_DB_ADDRESS }} 
          DB_USER: ${{ secrets.DB_USERNAME }}    
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SERVICE_NAME: ${{ secrets.DB_SERVICE_NAME }}
        with :
          host : ${{ secrets.AWS_WEB_ADDRESS }}
          username : ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script_stop : true
          script : |
            # 2. Git 레포지토리에서 최신 버전 Pull
            cd /home/ec2-user/Hairyz
            echo "Current directory:"
            pwd			 
            git pull origin main

      - name: Check current directory
        run: |
          echo "Current directory:"
          pwd
          ls -l /home/

      - name : Run Gradle build
        run : | 
            # 4. Gradle 빌드 수행
            chmod +x /home/runner/work/Hairyz/gradlew
            cd /home/runner/work/Hairyz/
            ./gradlew clean build
      
      - name : Rename WAR file
        run : | 
            # 5. 파일 이름 변경
            mv build/libs/*SNAPSHOT.war build/libs/project.war

      
      - name : Move WAR file to Tomcat
        run : | 
            # 6. war 파일 이동 
            mv /home/ec2-user/Hairyz/build/libs/project.war /home/ec2-user/apache-tomcat-10.1.31/webapps/
      
      - name : Test Oracle DB connection
        run : | 
            # 7. DB 연결 테스트 (오라클)
            echo "Testing Oracle DB connection"
            echo "SELECT * FROM member;" | sqlplus -S $DB_USER/$DB_PASSWORD@$DB_HOST:1521/$DB_SERVICE_NAME
      
      - name : Restart Tomcat
        run : | 
            # 8. 톰캣 재시작
            sudo /home/ec2-user/apache-tomcat-10.1.31/bin/shutdown.sh
            sudo /home/ec2-user/apache-tomcat-10.1.31/bin/startup.sh
