name : Deploy To EC2 

on :
  push : 
    branches :
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 비공개 SSH 키를 환경 변수에서 읽어 파일로 저장
      - name: Save private key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/private_key.pem
          chmod 600 /tmp/private_key.pem

      # 2. 원격 EC2 서버에 접속하여 배포 작업
      - name : SSH(원격접속)로 EC2에 접속하기
        uses : appleboy/ssh-action@v1.1.0
        env :           												
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }} 
        with :
          host : ${{ secrets.AWS_WEB_ADDRESS }}
          username : ${{ secrets.AWS_USER }}
          key: /tmp/private_key.pem  # 비공개 키 경로 지정
          script_stop : true
          script : |
            # 3. Git 레포지토리에서 최신 버전 Pull
            cd /home/ec2-user/Hairyz
            rm -rf src/main/resources/application.yml      				 
            git pull origin main

            # 4. 환경 변수 설정
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            
            # 5. Gradle 빌드 수행
            ./gradlew clean build

            # 6. Tomcat 포트 8081에서 이전 프로세스 종료
            sudo fuser -k -n tcp 8081 || true

            # 톰캣 재시작
            sudo /home/$EC2_USERNAME/apache-tomcat-10.1.31/bin/shutdown.sh
            sudo /home/$EC2_USERNAME/apache-tomcat-10.1.31/bin/startup.sh