name : Deploy To EC2 

on :
  push : 
    branches :
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name : Set API Keys as environment variables
        run : |      
            echo "KAKAO_KEY_ADMIN=${{ secrets.KAKAO_KEY_ADMIN }}" >> $GITHUB_ENV
            echo "GOOGLE_KEY=${{ secrets.GOOGLE_KEY }}" >> $GITHUB_ENV
            echo "KAKAO_KEY=${{ secrets.KAKAO_KEY }}" >> $GITHUB_ENV
            echo "NAVER_KEY=${{ secrets.NAVER_KEY }}" >> $GITHUB_ENV
            echo "FB_KEY=${{ secrets.FB_KEY }}" >> $GITHUB_ENV
            echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> $GITHUB_ENV
            echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> $GITHUB_ENV
            echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> $GITHUB_ENV
            echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
            echo "BOOTPAY_KEY=${{ secrets.BOOTPAY_KEY }}" >> $GITHUB_ENV
        shell: bash

      - name: save private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH key to agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      # 1. 원격 EC2 서버에 접속하여 배포 작업
      - name : SSH 접속 (EC2)
        uses : appleboy/ssh-action@master
        env : 
          DB_HOST: ${{ secrets.AWS_DB_ADDRESS }} 
          DB_USER: ${{ secrets.DB_USERNAME }}    
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SERVICE_NAME: ${{ secrets.DB_SERVICE_NAME }}
        with :
          host : ${{ secrets.AWS_WEB_ADDRESS }}
          username : ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script_stop : true
          script : |
            # 2. Git 레포지토리에서 최신 버전 Pull 
            cd /home/ec2-user/Hairyz	 
            git pull origin main

            # 3. build gradle
            ./gradlew clean build 
      
            # 4. 파일 이름 변경
            mv build/libs/*SNAPSHOT.war build/libs/project.war

            # 5. war 파일 이동 
            mv /home/ec2-user/Hairyz/build/libs/project.war /home/ec2-user/apache-tomcat-10.1.31/webapps/
            ls -al /home/ec2-user/apache-tomcat-10.1.31/webapps/

            # 6. 톰캣 재시작
            sudo /home/ec2-user/apache-tomcat-10.1.31/bin/shutdown.sh
            sudo /home/ec2-user/apache-tomcat-10.1.31/bin/startup.sh
            
